export const SCHOOL_NAMES = [
    "Bandaranayake College Gampaha",
    "Yashodara Devi Balika Vidyalaya Gampaha",
    "Rathnavali Balika Vidyalaya, Gampaha",
    "Holy Cross College Gampaha",
    "Bandaranayake Central College, Veyangoda",
    "Gurukula College, Kelaniya",
    "Royal College, Colombo",
    "Ananda College, Colombo",
    "Nalanda College, Colombo",
    "Thurstan College, Colombo",
    "Amal International School, Colombo",
    "Ave Maria Convent Branch School, Negombo",
    "Bishop's College, Colombo",
    "British School in Colombo",
    "Buddhist Ladies' College, Colombo",
    "C.M.S. Ladies' College, Colombo",
    "Carey College, Colombo, Colombo",
    "Colombo International School, Colombo",
    "Crescent Schools International, Colombo",
    "Crescent Schools International, Colombo",
    "Crescent Schools International, Wellampitiya",
    "De Mazenod College, Kandana",
    "Elizabeth Moir School, Colombo",
    "Gateway College, Dehiwala",
    "Gateway College, Negombo",
    "Hejaaz International School, Mount Lavinia[2]",
    "Learnium International School, Rajagiriya",
    "Lyceum International School, Kandana",
    "Lyceum International School, Wattala",
    "Lyceum International School, Yakkala",
    "Lyceum International School, Nugegoda",
    "Lyceum International School, Pandura",
    "Maris Stella College, Negombo",
    "Methodist College, Colombo",
    "Musaeus College, Colombo",
    "Overseas School of Colombo",
    "Royal Institute International School, Gampaha",
    "S. Thomas' College, Mount Lavinia",
    "S. Thomas' Preparatory School, Kollupitiya",
    "St. Joseph's Boys' College, Nugegoda",
    "St. Joseph's College, Colombo",
    "St. Joseph's College, Wattala",
    "St. Sebastian's College, Moratuwa",
    "St Benedict's College Colombo",
    "St Peter's College, Colombo",
    "St Peter's College, Udugampola",
    "Sumedha College, Gampaha",
    "Vidura College, Nawala",
    "Wesley College, Colombo",
    "ACE Institute International School, Colombo",
    "Adventist International School, Negombo",
    "Al Iman School, Dehiwala",
    "Al Iman School, Mount Lavinia",
    "Al Manar International School, Colombo",
    "Al Quds Arabic International school, Colombo",
    "Al Quds Arabic International school, Dehiwala",
    "Alethea International School, Dehiwala",
    "Alexandra College, Maradana",
    "Alexor International School, Colombo",
    "Alif International School, Dharga Town",
    "All Nations International School, Ganemulla",
    "Ape Lamai Special School, Gampaha",
    "Apple International School, Colombo",
    "Apple International School, Colombo",
    "Apple International School, Colombo",
    "Ashoka English Medium School, Horana",
    "Asian Grammar International School, Gothatuwa",
    "Asian International School, Battaramulla",
    "Asian International School, Colombo",
    "Atamie International School, Colombo",
    "Atamie International School, Ekala",
    "Atamie International School, Minuwangoda",
    "Atamie International School, Ragama",
    "Atamie International School, Wattala",
    "Beaconhall International School, Panadura",
    "Belvoir College International, Colombo",
    "Bond International School, Colombo",
    "Boswell International School, Kalutara",
    "Brightens International School, Colombo",
    "Brighton International School, Pugoda",
    "Brisbane International School, Nugegoda",
    "British International School, Kalutara",
    "British International School, Kiribathgoda",
    "Buckingham International School, Colombo",
    "Burhani Serandib School, Colombo",
    "Cambridge international school, Colombo",
    "Campbell International School, Colombo",
    "Campbell International School, Kotikawatta",
    "Christ King College, Pannipitiya",
    "Clayton College, Marandagahamula",
    "Colombo South International College, Nugegoda",
    "Dharul Hikma International School, Colombo",
    "Dhilshaath International College, Dematagoda",
    "Don Pedrick College, Horana",
    "Dr. Reijntes School For the Deaf, Moratuwa",
    "ESOL International School, Hanwella",
    "ESOL International School, Kaduwela",
    "ESOL International School, Maharagama",
    "East Asian International College, Nugegoda",
    "Eskola International School, Colombo",
    "Eureka International School, Kiribathgoda",
    "Garnet International School, Nittambuwa",
    "Gateway College Colombo",
    "Gathsemane College, Wattala",
    "Global International School, Colombo",
    "Golden Gate International School, Beruwala",
    "Gonsalvez College, Ja Ela",
    "Green Bridge International College, Kolonnawa",
    "HDI International School, Ja Ela",
    "Harcourts International School, Dehiwala",
    "Herald City College, Kadawatha",
    "Highlands College, Nugegoda",
    "Hilburn International School, Avissawella",
    "Hindu Ladies College, Colombo",
    "Holy Cross College, Kalutara",
    "Horizon College International, Malabe",
    "Horizon College International, Nugegoda",
    "House of Scholars International School, Panadura",
    "I GATE College, Thalawathugoda",
    "I GATE International School, Thalawathugoda",
    "Ikra International School, Colombo",
    "Ikra International School, Kolonnawa",
    "Ikra International School, Panadura",
    "Ilma International Girls' School, Colombo",
    "J.M.C. International School, Colombo",
    "J.M.C. International School, Colombo",
    "J.M.C. International School, Colombo",
    "J.M.C. International School, Kaduwela",
    "J.M.C. International School, Maharagama",
    "J.M.C. International School, Mulleriyawa",
    "JMC College International, Gampaha",
    "JMC College International, Kalutara",
    "JMC College International, Kiribathgoda",
    "JMC College International, Negombo",
    "JMC College International, Nittambuwa",
    "Jaya Sewana Special School, Kotte",
    "Kanza College, Colombo",
    "Kebel College, Nugegoda",
    "King's International School, Kapuwatta",
    "Kingston College international, Colombo",
    "Kingston College international, Mount lavinia",
    "Kingston College international, Wellawatta",
    "LPF School, Ratmalana",
    "Lakeland International American School, Ratmalana",
    "Lalith Athulathmudali College, Mount Lavinia",
    "Learning Excellence International College, Battaramulla",
    "Leeds International School, Horana",
    "Leeds International School, Kiribathgoda",
    "Leeds International School, Mathugama",
    "Leeds International School, Negombo",
    "Leeds International School, Panadura",
    "Leeds International School, Piliyandala",
    "Liberty International School, Colombo",
    "Liberty International School, Ethul Kotte",
    "Linfield Internanational School, Godagama",
    "Linfield Internanational School, Mortuwa",
    "Linfield Internanational School, Pannipitiya",
    "Linfield Internanational School, Piliyandala[3]",
    "Logos College, Colombo",
    "Lootah College, Minuwangoda",
    "Louvre College, Nugegoda",
    "Louvre College, Pannipitiya",
    "Loyola College, Negombo",
    "M.D Gunasena International School, Colombo",
    "Malwana International School, Malwana",
    "Maris Stella Branch College, Negombo",
    "Mayura Special School, Matugama",
    "Minaret International Girls' School, Dehiwala",
    "Minasro College, Gorakaduwa, Pelawatta",
    "Mount Hira International Boys school, Panadura",
    "Mount Hira International Girls school, Panadura",
    "Mubarak International School, Malwana",
    "Mukarmah International School, Negombo",
    "Mukarramah International School, Colombo",
    "Mukarramah International School, Colombo",
    "Mysticle Rose Institute International School, Ethulotte",
    "NCEF Buddhist College, Mulleriyawa",
    "Nakano College, Bandaragama",
    "Negombo International School, Negombo",
    "Negombo South International School, Negombo",
    "Negombo South International School, Negombo",
    "Negombo South International School, Nittambuwa",
    "Negombo South International School, Piliyandala",
    "Negombo Wisdom College, Negombo",
    "Nice International School, Negombo",
    "Noor International School, Kalutara",
    "OKI International School, Biyagama",
    "OKI International School, Kaduwela",
    "OKI International School, Kandana",
    "OKI International School, Kiribathgoda",
    "OKI International School, Kotikawatta",
    "OKI International School, Negombo",
    "OKI International School, Wattala",
    "Polymath College, Maharagama",
    "Princeway College, Avissawella",
    "Rathnaloka College, Matugama[5]",
    "Rawdha Aysha International School, Colombo",
    "Readway International College of Education, Dematagoda",
    "Reagent International School, Gampaha",
    "Rotary International School, Delkanda",
    "Rotary International School, Nugegoda",
    "Royal Institute International School, Colombo",
    "Royal Institute International School, Maharagama",
    "Royal Institute International School, Nugegoda",
    "Royal Institute International school, Colombo",
    "Sailan International School, Negombo",
    "Salford International School, Wattala",
    "School of Arts and Science, Colombo",
    "Shaffield International School, Pitakotte",
    "Sheffield International School, Gampaha",
    "Spectrum College, Mount Lavinia",
    "Springfield College, Colombo",
    "Sri Chandrasekara School for the Deaf, Moratuwa",
    "St. John's Girls College, Panadura",
    "St. Josephs College, Negombo",
    "St. Michael's College, Homagama",
    "St. Michael's College, Meegoda",
    "St. Michell's College, Negombo",
    "St. Nicholas International School, Negombo",
    "St. Nicholas' International College, Battaramulla",
    "St. Thomas International School, Seeduwa",
    "St.Joseph's School for the Deaf, Ragama",
    "Stafford International School, Colombo",
    "Sujatha Vidyalaya, Nugegoda",
    "Sukitha Special School, Kalutara",
    "Sumaga Special Needs School, Kelaniya",
    "Susitha Suwasetha Special School, Yakkala",
    "Sussex College, Gampaha",
    "Sussex College, Horana",
    "Sussex College, Kadawatha",
    "Sussex College, Kiribathgoda",
    "Sussex College, Negombo",
    "Sussex College, Nugegoda",
    "Taprobane College International, Kalutara",
    "Telford International School, Payagala",
    "The Chitra Lane School for Special Child, Colombo",
    "The School for the Blind, Ratmalana",
    "The School for the Deaf, Ratmalana",
    "The Study International School, Battaramulla",
    "The Study International School, Colombo",
    "Thihariya International School, Thihariya",
    "UNH International School, Kalutara",
    "UNH International School, Wattala",
    "Vidura College, Kalutara",
    "Vidura College, Kelaniya",
    "Westminster College, Mahara",
    "Willesden College International, Battaramulla",
    "Winway International School, Battaramulla",
    "Wisdom International School, Beruwala",
    "Wisdom International School, Dharga Town",
    "Wisdom International School, Maggona",
    "Wisdom International School, Negombo",
    "Wisdom International School, Pandura",
    "Wise International School, Kandana",
    "Wycherley International School, Colombo",
    "Wycherley International School, Gampaha",
    "York International School, Kadawatha",
    "York International School, Sapugaskanda",
    "York International School, Wattala",
    "Yoshida Shokonji International School, Makola"
]